logto-io/auth-wiki

src/layouts/Layout.astro
=> chore: add plausible

package.json, pnpm-lock.yaml, src/articles/identity-management.mdx, src/articles/implicit-flow.mdx, src/mdx-components/Resources.astro, src/mdx-components/SeeAlso.astro, src/pages/[slug].astro
add `<Resources />` component for external links
=> feat: resources component

src/articles/authorization-code-flow.mdx, src/articles/device-flow.mdx, src/articles/implicit-flow.mdx, src/articles/jit-provisioning.mdx, src/articles/jwt.mdx, src/articles/management-api.mdx, src/articles/multi-tenancy.mdx, src/articles/opaque-token.mdx, src/articles/passkey.mdx, src/articles/rbac.mdx, src/articles/role.mdx, src/articles/scope.mdx, src/articles/webauthn.mdx, src/articles/webhook.mdx, src/mdx-components/Resources.astro, src/pages/[slug].astro, src/pages/index.astro
update internal/external links to use built-in components
=> refactor: update links

src/articles/rbac.mdx, src/articles/role.mdx
refactor: update descriptions for rbac and role
=> refactor: update descriptions for rbac and role

src/components/ByLogto.astro, src/components/Topbar.astro
reduce topbar action button content on small screens
=> refactor: optimize responsiveness

src/articles/auth.mdx
add disambiguation page for "auth"
=> chore: add auth page

.github/workflows/main.yml
run basic jobs for pull requests
=> ci: add main workflow

src/articles/client-credentials-flow.mdx, src/articles/client.mdx, src/articles/oauth-2.0-grant.mdx, src/articles/oauth-2.1.mdx, src/articles/pkce.mdx, src/articles/refresh-token.mdx
use more precise terms and enrich OAuth 2.1 content
=> chore: improve OAuth 2.1 content

src/components/Share.astro, src/components/Topbar.astro, src/layouts/Layout.astro, src/mdx-components/Resources.astro, src/mdx-components/SeeAlso.astro, src/pages/[slug].astro, src/pages/index.astro, src/phrases/en.ts, src/phrases/index.ts, src/phrases/zh.ts
- add i18n in website layout
- add alternate urls in `<head>`
=> feat: layout i18n

src/phrases/ar.ts, src/phrases/de.ts, src/phrases/en.ts, src/phrases/es.ts, src/phrases/fr.ts, src/phrases/ja.ts, src/phrases/ko.ts, src/phrases/nl.ts, src/phrases/zh.ts
use more concise content for description phrases
=> refactor: optimize description content

src/content/terms/ar/abac.mdx, src/content/terms/ar/xacml.mdx, src/content/terms/de/abac.mdx, src/content/terms/de/xacml.mdx, src/content/terms/en/abac.mdx, src/content/terms/en/xacml.mdx, src/content/terms/es/abac.mdx, src/content/terms/es/xacml.mdx, src/content/terms/fr/abac.mdx, src/content/terms/fr/xacml.mdx, src/content/terms/ja/abac.mdx, src/content/terms/ja/xacml.mdx, src/content/terms/ko/abac.mdx, src/content/terms/ko/xacml.mdx, src/content/terms/nl/abac.mdx, src/content/terms/nl/xacml.mdx, src/content/terms/zh-Hant/abac.mdx, src/content/terms/zh-Hant/xacml.mdx, src/content/terms/zh/abac.mdx, src/content/terms/zh/xacml.mdx, src/pages/[slug].astro
=> chore: add xacml term

astro.config.mjs, package.json, pnpm-lock.yaml, src/layouts/Layout.astro, src/pages/[lang]/[...slug]/cover.png.ts, src/pages/[slug].astro, src/utils/cover.ts, src/utils/string.ts
generate article images based on title
=> feat: generate cover for articles

src/content/terms/en/jit-provisioning.mdx
add internal links to jit provisioning article
=> chore: add update jit-provisioning.mdx

src/content/terms/en/rbac.mdx
=> refactor: update rbac content

src/content/terms/en/magic-link.mdx, src/content/terms/en/opaque-token.mdx, src/content/terms/en/passwordless.mdx
1. remove Logto mentions in "opaque token"
2. add internal links in "opaque token", "passwordless" and "magic links".
=> chore: remove Logto mentions and add internal links

src/content/terms/en/role.mdx
=> refactor: update role content

src/content/terms/en/webhook.mdx
refactor: update webhook content
=> refactor: update webhook content

src/content/terms/en/webauthn.mdx
1. Add an example and image for webauthn workflow
2. Add "WebAuthn and OIDC"
3. Add more internal links
=> refactor: update webauthn.mdx

src/content/terms/en/device-flow.mdx
=> refactor: update device flow

src/content/terms/en/passkey.mdx
1. Add a use case and code mermaid for Passkey workflow.
2. Add the content about why passkeys are more secure than TOTP.
=> refactor: update passkey.mdx

src/content/terms/en/multi-tenancy.mdx
Make it clearer, simpler, and remove the theoretical parts. Added a few diagrams.
=> refactor: update multi-tenancy.mdx

src/components/LanguageSelector.astro
=> fix: language selector style

src/content/terms/en/csprng.mdx
=> chore: add intro to CSPRNG

src/pages/[slug].astro, src/phrases/ar.ts, src/phrases/de.ts, src/phrases/en.ts, src/phrases/es.ts, src/phrases/fr.ts, src/phrases/it.ts, src/phrases/ja.ts, src/phrases/ko.ts, src/phrases/nl.ts, src/phrases/pt-br.ts, src/phrases/pt-pt.ts, src/phrases/zh-hant.ts, src/phrases/zh.ts
prepend "what is" for better discoverability
=> refactor: update page title

src/content/terms/en/single-sign-on.mdx
Thx to this [issue](https://github.com/logto-io/auth-wiki/issues/74). This PR enhances the single sign-on content by incorporating additional details about how the IdP automatically authenticates users using a valid session cookie.
=> chore: polish the sso content

src/content/terms/en/authentication.mdx
improve authentication content
=> refactor: update authentication.mdx

src/content/terms/en/otp.mdx
Add different types of OTP and security considerations.
=> refactor: update otp

src/content/terms/en/magic-link.mdx
=> refactor: update magic link

src/content/terms/en/passwordless.mdx
=> refactor: update passwordless

src/components/Card.astro
=> refactor: update card design

src/content/terms/en/opaque-token.mdx
Make it concise and add more contents.
=> refactor: update opaque token wiki

src/content/terms/en/authorization-code-flow.mdx
refactor: update authorization code flow wiki
=> refactor: update authorization code flow wiki

package.json, pnpm-lock.yaml
=> chore: bump dependencies

src/content/terms/en/backup code.mdx
Auth Wiki: add a new wiki about backup code
=> refactor: update backup code wiki

src/content/terms/en/authorization-server-metadata.mdx
add authorization server metadata docs
=> feat: add authorization server metadata docs
